Prevent error on fine logging:
javax.resource.ResourceException: Unable to get managed connection for
java:/XXX
         at
com.seeburger.inbox.server.InboxServerHazelcast.updateTask(InboxServerHazelcast.java:343)
         at
com.seeburger.engine.inbox.EngineWorkerThread.doWork(EngineWorkerThread.java:232)
         at
com.seeburger.inbox.server.worker.AbstractWorker.run(AbstractWorker.java:56)
 Caused by: javax.resource.ResourceException: IJ000453: Unable to get
managed connection for java:/XXX
         at
org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:390)
         at
org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:368)
         at
org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:464)
         at
com.hazelcast.jca.ConnectionFactoryImpl.getConnection(ConnectionFactoryImpl.java:76)
         at
com.hazelcast.jca.ConnectionFactoryImpl.getConnection(ConnectionFactoryImpl.java:66)
         at
com.seeburger.inbox.server.InboxServerHazelcast.getTransactionalTasksMap(InboxServerHazelcast.java:781)
         at
com.seeburger.inbox.server.InboxServerHazelcast.updateTask(InboxServerHazelcast.java:339)
         ... 2 more
 Caused by: javax.resource.ResourceException: IJ000658: Unexpected
throwable while trying to create a connection: null
         at
org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:371)
         at
org.jboss.jca.core.connectionmanager.pool.AbstractPool.getTransactionNewConnection(AbstractPool.java:495)
         at
org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:374)
         at
org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:329)
         ... 8 more
 Caused by: java.lang.IllegalArgumentException: Timeout must be
positive!
         at
com.hazelcast.transaction.TransactionOptions.setTimeout(TransactionOptions.java:99)
         at
com.hazelcast.jca.HazelcastTransactionImpl.createTransaction(HazelcastTransactionImpl.java:123)
         at
com.hazelcast.jca.XAResourceWrapper.setInner(XAResourceWrapper.java:132)
         at
com.hazelcast.jca.XAResourceWrapper.toString(XAResourceWrapper.java:140)
         at java.lang.String.valueOf(String.java:2854) [rt.jar:1.7.0_51]
         at java.lang.StringBuilder.append(StringBuilder.java:128)
[rt.jar:1.7.0_51]
         at
org.jboss.jca.core.tx.jbossts.XAResourceWrapperImpl.toString(XAResourceWrapperImpl.java:246)
         at java.lang.String.valueOf(String.java:2854) [rt.jar:1.7.0_51]
         at java.lang.StringBuffer.append(StringBuffer.java:232)
[rt.jar:1.7.0_51]
         at
org.jboss.jca.core.connectionmanager.listener.TxConnectionListener.toString(TxConnectionListener.java:699)
         at
org.jboss.jca.core.connectionmanager.listener.AbstractConnectionListener.toString(AbstractConnectionListener.java:446)
         at java.lang.String.valueOf(String.java:2854) [rt.jar:1.7.0_51]
         at java.lang.StringBuilder.append(StringBuilder.java:128)
[rt.jar:1.7.0_51]
         at
com.hazelcast.jca.ManagedConnectionImpl.addConnectionEventListener(ManagedConnectionImpl.java:66)
         at
org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.createConnectionListener(TxConnectionManagerImpl.java:588)
         at
org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:767)
         at
org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:343)
         ... 11 more